[project]
name = "text-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YASH SINGH", email = "singhyash9009670@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = []

[project.scripts]
text-summarizer = "text_summarizer:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
